export type CSVStockObject = {
    'Item name': string;
    'Variations': string;
    'Option set 1': string;
    'Option 1': string;
    'Option set 2': string;
    'Option 2': string;
    'Option set 3': string;
    'Option 3': string;
    'Option set 4': string;
    'Option 4': string;
    'Is variation visible? (Yes/No)': string;
    'Price': string;
    'On sale in Online Store?': string;
    'Regular price (before sale)': string;
    'Tax rate (%)': string;
    'Track inventory? (Yes/No)': string;
    'Quantity': string;
    'Low stock threshold': string;
    'SKU': string;
    'Barcode': string;
    'Description (Online Store and Invoices only)': string;
    'Category': string;
    'Display colour in POS checkout': string;
    'Image 1': string;
    'Image 2': string;
    'Image 3': string;
    'Image 4': string;
    'Image 5': string;
    'Image 6': string;
    'Image 7': string;
    'Display item in Online Store? (Yes/No)': string;
    'SEO title (Online Store only)': string;
    'SEO description (Online Store only)': string;
    'Shipping weight [kg] (Online Store only)': string;
    'Item id (Do not change)': string;
    'Variant id (Do not change)': string;
    'Valeur par défaut': number;
};
