export const ROUTES = {
    PRODUITS: '/',
    TA_NOU_BIO: '/?category=Ta+Nou+Bio',
    NOS_PANIERS_BIO: '/?category=Nos+Paniers+Bio',
    NOS_PANIERS_MANRINA: '/?category=Nos+Paniers+Manrina',
    PANIER: '/panier',
    PAIEMENT: '/payment',
    ARTICLE: (productId: string) => `/article/${productId}`,
    REGISTER: '/register',
    ADMIN: {
        LOGIN: '/admin-login',
        DASHBOARD: '/admin/dashboard',
        STOCK: '/admin/stock',
        COMMANDES: '/admin/commandes',
        GROWERS: '/admin/producteurs',
        CLIENTS: '/admin/clients',
    },
    GROWER: {
        LOGIN: '/login',
        PROFILE: '/producteur/mon-profil',
        STOCKS: '/producteur/stocks',
        MARKET: '/producteur/mon-marche',
        STAND: '/producteur/mon-marche/mon-stand',
    },
    DELIVERER: {
        LOGIN: '/livreur/login',
        ORDERS: '/livreur/commandes',
        DELIVERIES: '/livreur/livraisons',
        PROFILE: '/livreur/profile',
    },
    CUSTOMER: {
        LOGIN: '/login',
        PROFILE: '/client/mon-profil/informations-personnelles',
        ADDRESSES: '/client/mon-profil/adresses-de-livraison',
        ORDERS: '/client/mes-commandes',
    },
    VALIDATION: {
        DELIVERY: '/client/validation-commande/livraison',
        SUMMARY: '/client/validation-commande/resume-commande',
    },
    MARCHES_TERRAIN: '/manrina-an-peyi-a',
} as const;
